### ISSUE TITLE
Style decision: Should String() of an object add the the newline at the end

### ISSUE THREAD

**Issue by RincewindsHat** [NETWAYS/go-icingadsl#18]
Should

```
foo := CheckCommand{}
foo.String()
```

generate a `\n` after the closing `}` or should that be left to the caller?

**Comment by RincewindsHat** [comment]
@martialblog

**Comment by martialblog** [comment]
Good question. It's seems simpler to add something than to remove something.

**Comment by RincewindsHat** [comment]
Excellent point. I will change the code then
